### PR TITLE
Fix #25 Add "please note" clause

### LINKED ISSUE #25: Add 'Please note...' to travel reimbursement question subtext
screen shot 2017-10-30 at 9 16 02 pm

`Please note: participants will only be reimbursed after submitting and demoing their project.`

### PR DESCRIPTION
**Pull request by jumbosushi**
Fix #25

### CODE REVIEW

**Comment by luceliu** [comment]
can you add it as an _li_ instead? So that it goes under the 'max of $200' bullet point @jumbosushi

**Comment by jumbosushi** [comment]
done

**Comment by luceliu** [comment]
as a separate li tho @jumbosushi ok nitpicky but ya

**Review by d4l3k — APPROVED** [review]
👍

**Pull request merged**
